language: node_js
node_js:
- node
- '4'
- '0.12'
- '0.10'
before_script:
- npm install -g gulp mocha istanbul
after_script:
- npm run coveralls
- npm run lint
branches:
  only:
    - master
deploy:
  on:
    branch: master
  api_key:
    secure: evf2H7a2sxgaulNInrrCCx7I7a/QJzIdPC/Ycp79i2OK16jLKwXZXMx+1b5Xe/bzf3egylDt3IToHIsD+QkiaCCrwEWjO7BSVPp4tMUx5sSjM0JTxYDpgtVm0P/3f6cbYN+2GNRyfVR0/YaYeFovvDRNP2pY7BIT6waH1vTwpFxrEIzsMGDLHxBo3Ax1NZzerQREIxmcEFoy0c3LNReq7m9kJaqv75Sgj0UWRP9EEUftdNbywP6ICle+pwHO2sVF+ccZNBenqZaJnvr2bhLYqVURR+Mi5Q89eRrdtvMJ6G7DM/x2GP1uBPaJVTuhjQe/d1sP3rWMiwnE0xQk8A1KGpLfogbcGlWxWYlclk6JpggThuzRdJINsI1Ya94wdsF0iORElu2u5lpzFGx9q5pjbKsh0HlpzsjZbOceYp330x2TBWHPJ2sn8Dir3CHG/LDU0t68rCtkz/0wzqD0MtC7fYQ78+kTlImtZZGA9p5XUnj9WX3/kc38x2vo1aE+N3WGWjDD+n8m944DN6a2t5LlCskpNK4eiE51IDte1bGlVOQ8f5UKmc8mKuUtjyGjgdEF/VBgrpeE2dbIntYZtUdbODMNgm5WOxh65RTVTXNhQH6ojdMwTV1JSN/JqSTL4XvJ8JWWuf8NNg0I8SjxZJ6bNuxgQjVvGagImF7mmEZ+R+c=
